# **Getting Started with Python!**

## NumPy

In the previous notebook we learnt the basics of Python and why it's so popular for application in AI. We also learnt about the different data types available in Python, what modules and packages are along with different control options. Now let's get started with **NumPy** (short for Numerical'Num' Python'Py')  one of the most popular packages available in Python for performing scientfic calculcations especially those related to arrays. Let's get started! 

## Arrays

NumPy arrays in python are basically grids of values of the same data type. Each element of a NumPy array has a non-negative index associated with it. When dealing with arrays, we come across a useful term called **shape** which gives the size of the array along each dimension. 

In [ ]:
import numpy as np #importing numpy package 
a = np.array([1,2,3]) #initializing an array with the elements given in the brakcets
print (a)

[1 2 3]


Let's check the datatype for the array 'a'

In [ ]:
print (type(a)) #write your code for checking the datatype here

<class 'numpy.ndarray'>


In [ ]:
#Creating an array with more than one dimension
b = np.array([[1, 2], [3, 4]]) 
print (b)

[[1 2]
 [3 4]]


In [ ]:
#let's check the shape of the arrays created so far
print("Shape of array 'a' is:",(a.shape))
print("Shape of array 'b' is:",(b.shape))

Shape of array 'a' is: (3,)
Shape of array 'b' is: (2, 2)


In [ ]:
#accessing elements of the array using the index
print(a[0], a[1], a[2]) 
print(b[0][0]) #printing the first row first, first column element

1 2 3
1


In [ ]:
#another way of printing a particular element of an array
print(b[0,1])

2


In [ ]:
#using the arange function to create an array
c=np.arange(4) #prints the first four elements as 0 onwards by default
print (c)
d=np.arange(1,7)#specifying start point and end point
print (d)

[0 1 2 3]
[1 2 3 4 5 6]


In [ ]:
# Create the following array with given shape (3, 4). Name the array 'new'
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
new = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print (new)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
# Slicing is being used to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; new_sub is the following array of shape (2, 2):

new_sub = new[:2, 1:3]
print(new_sub)

[[2 3]
 [6 7]]


**Integer array indexing** 

When you index into numpy arrays using slicing, the resulting array will always be a subarray of the original array. In contrast, integer array indexing allows you to construct arbitrary arrays using the data from another array. Here is an example:

In [ ]:
a = np.array([[1,2], [3, 4], [5, 6]])

# Example of integer array indexing.
# Returned array will have shape (3,) and


[1 4 5]
(3,)


In [ ]:
# The above example of integer array indexing is equivalent to this:
print(

# When using integer array indexing, you can reuse the same
# element from the source array:
print(

# Equivalent to the previous integer array indexing example
print(

[1 4 5]
[2 2]
[2 2]


We can also use integer indexing to mutate specific elements of an array

In [ ]:
# Create an array of indices
b = np.array([1, 0, 1])
print(b)

# Select one element from each row of a using the indices in b
print(

[1 0 1]
[2 3 6]


In [ ]:
# Mutate one element from each row of a using the indices in b
a[np.arange(3), b] += 10

print(a)

[[ 1 12]
 [13  4]
 [ 5 16]]


## Datatypes in NumPy Arrays

In [ ]:
roll_no = np.array([23, 46])   # Let numpy choose the datatype
print(roll_no.dtype)         # Prints "int64"

marks = np.array([65.5, 88.0])   # Let numpy choose the datatype
print(marks.dtype)             # Prints "float64"

int64
float64


In [ ]:
x = np.array([1, 2], dtype=np.int64)   # Force a particular datatype
print(x.dtype)                         # Prints "int64"

int64


**Array Mathematics**

Basic mathematical operations are available on arrays in an elementwise manner. This can be done using either operators like (+,-,* etc.) or as built-in functions within the package itself.

In [ ]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementwise sum; both produce the array
# [[ 6.0  8.0]
#  [10.0 12.0]]
print(
print(

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [ ]:
#write a code to create two arrays X & Y with the following elements and print their difference
# X = [[13.0 7.0]
#     [4.0 47.0]]
# Y = [[16.0 14.0] 
#     [1.0 23.0]]

In [ ]:
X = np.array([[13.0,7.0],[4.0,47.0]], dtype=np.float64)
Y = np.array([[16.0,14.0],[1.0,23.0]], dtype=np.float64)
print (X-Y)
print(np.subtract(X, Y))

[[-3. -7.]
 [ 3. 24.]]
[[-3. -7.]
 [ 3. 24.]]


In [ ]:
#to perform elementwise multiplication
print(x * y)
print(np.multiply(x, y))

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


Note that this is different from performing matrix multiplication. The * operator is only used for elementwise multiplication.

In [ ]:
#to perform elementwise division
print(x / y)
print(

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


Sorting NumPy Arrays

In [ ]:
a = np.array([1, 2, 3, 4, 5, 2, 1])
print(a)

[1 2 3 4 5 2 1]


In [ ]:
np.sort(a) #function for sorting elements in ascending order
print (np.sort(a))

[1 1 2 2 3 4 5]


In [ ]:
np.flip(np.sort(a)) #function for sorting elements in descending order
print (np.flip(np.sort(a)))

[5 4 3 2 2 1 1]


In [ ]:
np.flip(np.sort(a))[:2]  #slicing and sorting
print (np.flip(np.sort(a))[:2])

[5 4]


## Manipulating NumPy Arrays

The function reshape() allows manipulation of shape of array without altering its elements. The syntax for this function is illustrated below

In [ ]:
x=np.arange(12) #creating 12*1 array
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
y=x.reshape(6,2) #changing shape from 12*1 to 6*2 array
print(y)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]


Just like concatenation of lists or strings we can concatenate arrays as well. In the following example we concatenate three one-dimensional arrays to one array. The elements of the second array are appended to the first array. After this the elements of the third array are appended.

In [ ]:
x = np.array([
y = np.array([
z = np.array([
print(x)
print(y)
print(z)
c = np.concatenate((x,y,z)) #function to perform concatenation
print(c)

[ 3 12]
[12  4  7]
[2 6 8]
[ 3 12 12  4  7  2  6  8]


If we are concatenating multidimensional arrays, we can concatenate the arrays according to axis. Arrays must have the same shape to be concatenated with concatenate(). In the case of multidimensional arrays, we can arrange them according to the axis. The default value is axis = 0:

In [ ]:
x = np.array([[2,4],[7,9]])

x=x.reshape(1,4)
y = np.array([10,12,14,16])

y=y.reshape(1,4)
c = np.concatenate((x,y),axis=1)


[[2 4]
 [7 9]]
[10 12 14 16]
[[ 2  4  7  9 10 12 14 16]]


# Pandas

Pandas is built on top of NumPy and is one of the most popular open-source packages available in Python. It's main utility lies in providing a large number of functions for handling real world data

# **Data Frame**

A Data frame is a two-dimensional data structure, i.e., data is aligned in a tabular fashion in rows and columns.

**Pro-tip**: To have a list of useful functions and commands always at your fingertips you can save this [cheatsheet](https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Numpy_Python_Cheat_Sheet.pdf) here!